create type "public"."haushalt_stage" as enum ('unvollstaendig', 'erfasst', 'kennt_das_projekt', 'infoveranstaltung', 'interessiert', 'warte_auf_unterschrift', 'skeptisch', 'kw_startkunde', 'kw_standbykunde', 'kw_perspektivkunde', 'will_nicht');

alter table "public"."personen" drop constraint "personen_haushalt_id_fkey";

drop index if exists "public"."idx_personen_haushalt_id";


  create table "public"."haushalt_person_bewohner" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "haushalt_id" uuid,
    "person_id" uuid
      );


alter table "public"."haushalt_person_bewohner" enable row level security;

alter table "public"."haushalte" add column "stage" public.haushalt_stage default 'unvollstaendig'::public.haushalt_stage;

alter table "public"."haushalte" add column "vermieter_id" uuid;

alter table "public"."personen" drop column "haushalt_id";

CREATE UNIQUE INDEX haushalt_person_bewohner_pkey ON public.haushalt_person_bewohner USING btree (id);

alter table "public"."haushalt_person_bewohner" add constraint "haushalt_person_bewohner_pkey" PRIMARY KEY using index "haushalt_person_bewohner_pkey";

alter table "public"."haushalt_person_bewohner" add constraint "haushalt_person_bewohner_haushalt_id_fkey" FOREIGN KEY (haushalt_id) REFERENCES public.haushalte(id) not valid;

alter table "public"."haushalt_person_bewohner" validate constraint "haushalt_person_bewohner_haushalt_id_fkey";

alter table "public"."haushalt_person_bewohner" add constraint "haushalt_person_bewohner_person_id_fkey" FOREIGN KEY (person_id) REFERENCES public.personen(id) not valid;

alter table "public"."haushalt_person_bewohner" validate constraint "haushalt_person_bewohner_person_id_fkey";

alter table "public"."haushalte" add constraint "haushalte_vermieter_id_fkey" FOREIGN KEY (vermieter_id) REFERENCES public.personen(id) not valid;

alter table "public"."haushalte" validate constraint "haushalte_vermieter_id_fkey";

grant delete on table "public"."haushalt_person_bewohner" to "anon";

grant insert on table "public"."haushalt_person_bewohner" to "anon";

grant references on table "public"."haushalt_person_bewohner" to "anon";

grant select on table "public"."haushalt_person_bewohner" to "anon";

grant trigger on table "public"."haushalt_person_bewohner" to "anon";

grant truncate on table "public"."haushalt_person_bewohner" to "anon";

grant update on table "public"."haushalt_person_bewohner" to "anon";

grant delete on table "public"."haushalt_person_bewohner" to "authenticated";

grant insert on table "public"."haushalt_person_bewohner" to "authenticated";

grant references on table "public"."haushalt_person_bewohner" to "authenticated";

grant select on table "public"."haushalt_person_bewohner" to "authenticated";

grant trigger on table "public"."haushalt_person_bewohner" to "authenticated";

grant truncate on table "public"."haushalt_person_bewohner" to "authenticated";

grant update on table "public"."haushalt_person_bewohner" to "authenticated";

grant delete on table "public"."haushalt_person_bewohner" to "postgres";

grant insert on table "public"."haushalt_person_bewohner" to "postgres";

grant references on table "public"."haushalt_person_bewohner" to "postgres";

grant select on table "public"."haushalt_person_bewohner" to "postgres";

grant trigger on table "public"."haushalt_person_bewohner" to "postgres";

grant truncate on table "public"."haushalt_person_bewohner" to "postgres";

grant update on table "public"."haushalt_person_bewohner" to "postgres";

grant delete on table "public"."haushalt_person_bewohner" to "service_role";

grant insert on table "public"."haushalt_person_bewohner" to "service_role";

grant references on table "public"."haushalt_person_bewohner" to "service_role";

grant select on table "public"."haushalt_person_bewohner" to "service_role";

grant trigger on table "public"."haushalt_person_bewohner" to "service_role";

grant truncate on table "public"."haushalt_person_bewohner" to "service_role";

grant update on table "public"."haushalt_person_bewohner" to "service_role";


